# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='skeleton',
            field=models.FileField(default=0, upload_to='uploads/skeleton'),
            preserve_default=False,
        ),
    ]
