# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='message',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
