# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20160226_0219'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.RemoveField(
            model_name='file',
            name='submission',
        ),
        migrations.AddField(
            model_name='assignment',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
