# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0008_auto_20160314_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='status',
            new_name='skeleton',
        ),
    ]
