; ModuleID = './iconfig.bc'
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.gs_main_instance_s = type { %struct.gs_memory_s*, i32, i64, i32, i32, i32, i32, i32, %struct.gs_file_path_s, [2 x i64], i8*, %struct.ref_s, i32 (%struct._IO_FILE*, i8**)*, %struct.display_callback_s*, %struct.gs_context_state_s*, i8*, i32 }
%struct.gs_memory_s = type { %struct.gs_memory_s*, %struct.gs_memory_procs_s, %struct.gs_lib_ctx_s*, %struct.gs_memory_s*, %struct.gs_memory_s* }
%struct.gs_memory_procs_s = type { i8* (%struct.gs_memory_s*, i32, i8*)*, i8* (%struct.gs_memory_s*, i8*, i32, i8*)*, void (%struct.gs_memory_s*, i8*, i8*)*, %struct.gs_memory_s* (%struct.gs_memory_s*)*, void (%struct.gs_memory_s*, %struct.gs_memory_status_s*)*, void (%struct.gs_memory_s*, i32, i8*)*, void (%struct.gs_memory_s*)*, i8* (%struct.gs_memory_s*, i32, i8*)*, i8* (%struct.gs_memory_s*, %struct.gs_memory_struct_type_s*, i8*)*, i8* (%struct.gs_memory_s*, %struct.gs_memory_struct_type_s*, i8*)*, i8* (%struct.gs_memory_s*, i32, i32, i8*)*, i8* (%struct.gs_memory_s*, i32, i32, i8*)*, i8* (%struct.gs_memory_s*, i32, %struct.gs_memory_struct_type_s*, i8*)*, i8* (%struct.gs_memory_s*, i32, %struct.gs_memory_struct_type_s*, i8*)*, i32 (%struct.gs_memory_s*, i8*)*, %struct.gs_memory_struct_type_s* (%struct.gs_memory_s*, i8*)*, i8* (%struct.gs_memory_s*, i32, i8*)*, i8* (%struct.gs_memory_s*, i32, i8*)*, i8* (%struct.gs_memory_s*, i8*, i32, i32, i8*)*, void (%struct.gs_memory_s*, i8*, i32, i8*)*, i32 (%struct.gs_memory_s*, %struct.gs_gc_root_s*, %struct.gs_ptr_procs_s*, i8**, i8*)*, void (%struct.gs_memory_s*, %struct.gs_gc_root_s*, i8*)*, void (%struct.gs_memory_s*, i32)* }
%struct.gs_memory_status_s = type { i64, i64, i32 }
%struct.gs_memory_struct_type_s = type opaque
%struct.gs_gc_root_s = type opaque
%struct.gs_ptr_procs_s = type opaque
%struct.gs_lib_ctx_s = type { %struct.gs_memory_s*, %struct._IO_FILE*, %struct._IO_FILE*, %struct._IO_FILE*, %struct._IO_FILE*, i32, i32, i32, i8*, i8*, i32 (i8*, i8*, i32)*, i32 (i8*, i8*, i32)*, i32 (i8*, i8*, i32)*, i32 (i8*)*, i64, i8*, %struct.name_table_s*, i32, %struct.gx_io_device_s**, i32, i32, [2 x i64], %struct.gs_font_dir_s*, i32, i8*, i32, i8*, %struct.gs_fapi_server_s** }
%struct._IO_FILE = type { i32, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, i8*, %struct._IO_marker*, %struct._IO_FILE*, i32, i32, i64, i16, i8, [1 x i8], i8*, i64, i8*, i8*, i8*, i8*, i64, i32, [20 x i8] }
%struct._IO_marker = type { %struct._IO_marker*, %struct._IO_FILE*, i32 }
%struct.name_table_s = type opaque
%struct.gx_io_device_s = type opaque
%struct.gs_font_dir_s = type opaque
%struct.gs_fapi_server_s = type opaque
%struct.gs_file_path_s = type { %struct.ref_s, %struct.ref_s, i8*, i8*, i32 }
%struct.ref_s = type { %struct.tas_s, %union.v }
%struct.tas_s = type { i16, i16, i32 }
%union.v = type { i64 }
%struct.display_callback_s = type opaque
%struct.gs_context_state_s = type opaque
%struct.build_function_type_s = type { i32, i32 (%struct.gs_context_state_s*, %struct.ref_s*, %struct.gs_function_params_s*, i32, %struct.gs_function_s**, %struct.gs_memory_s*)* }
%struct.gs_function_params_s = type { i32, float*, i32, float* }
%struct.gs_function_s = type { %struct.gs_function_head_s, %struct.gs_function_params_s }
%struct.gs_function_head_s = type { i32, %struct.gs_function_procs_s }
%struct.gs_function_procs_s = type { i32 (%struct.gs_function_s*, float*, float*)*, i32 (%struct.gs_function_s*, float*, float*, i32*)*, void (%struct.gs_function_s*, %struct.gs_function_info_s*)*, i32 (%struct.gs_function_s*, %struct.gs_param_list_s*)*, i32 (%struct.gs_function_s*, %struct.gs_function_s**, %struct.gs_range_s*, %struct.gs_memory_s*)*, void (%struct.gs_function_params_s*, %struct.gs_memory_s*)*, void (%struct.gs_function_s*, i32, %struct.gs_memory_s*)*, i32 (%struct.gs_function_s*, %struct.stream_s*)* }
%struct.gs_function_info_s = type { %struct.gs_data_source_s*, i64, %struct.gs_function_s**, i32 }
%struct.gs_data_source_s = type opaque
%struct.gs_param_list_s = type opaque
%struct.gs_range_s = type { float, float }
%struct.stream_s = type opaque
%struct.op_def = type { i8*, i32 (%struct.gs_context_state_s*)* }
%struct.i_plugin_client_memory_s = type { i8*, i8* (%struct.i_plugin_client_memory_s*, i32, i8*)*, void (%struct.i_plugin_client_memory_s*, i8*, i8*)* }
%struct.i_plugin_instance_s = type { %struct.i_plugin_descriptor_s* }
%struct.i_plugin_descriptor_s = type { i8*, i8*, void (%struct.i_plugin_instance_s*, %struct.i_plugin_client_memory_s*)* }

@gs_main_instance_init_values = constant %struct.gs_main_instance_s { %struct.gs_memory_s* null, i32 20000, i64 0, i32 0, i32 -1, i32 0, i32 0, i32 1, %struct.gs_file_path_s zeroinitializer, [2 x i64] zeroinitializer, i8* null, %struct.ref_s zeroinitializer, i32 (%struct._IO_FILE*, i8**)* null, %struct.display_callback_s* null, %struct.gs_context_state_s* null, i8* null, i32 0 }, align 8
@gs_init_files = constant [458 x i8] c"gs_btokn.ps\00gs_dps1.ps\00gs_dps2.ps\00gs_type1.ps\00gs_lev2.ps\00gs_res.ps\00gs_typ42.ps\00gs_cidfn.ps\00gs_cidcm.ps\00gs_fntem.ps\00gs_cidtt.ps\00gs_cidfm.ps\00gs_cmap.ps\00gs_setpd.ps\00gs_fapi.ps\00gs_typ32.ps\00gs_frsd.ps\00gs_ll3.ps\00gs_mex_e.ps\00gs_mro_e.ps\00gs_pdf_e.ps\00gs_wan_e.ps\00pdf_ops.ps\00gs_l2img.ps\00pdf_rbld.ps\00pdf_base.ps\00pdf_draw.ps\00pdf_font.ps\00pdf_main.ps\00pdf_sec.ps\00gs_css_e.ps\00gs_cff.ps\00gs_mgl_e.ps\00gs_agl.ps\00gs_ttf.ps\00gs_icc.ps\00gs_dps.ps\00gs_dpnxt.ps\00gs_epsf.ps\00gs_pdfwr.ps\00\00", align 16
@gs_init_files_sizeof = constant i32 458, align 4
@gs_emulators = constant [67 x i8] c"PostScript\00PostScriptLevel1\00PostScriptLevel2\00PostScriptLevel3\00PDF\00\00", align 16
@gs_emulators_sizeof = constant i32 67, align 4
@build_function_type_table = constant [5 x %struct.build_function_type_s] [%struct.build_function_type_s { i32 4, i32 (%struct.gs_context_state_s*, %struct.ref_s*, %struct.gs_function_params_s*, i32, %struct.gs_function_s**, %struct.gs_memory_s*)* @gs_build_function_4 }, %struct.build_function_type_s { i32 0, i32 (%struct.gs_context_state_s*, %struct.ref_s*, %struct.gs_function_params_s*, i32, %struct.gs_function_s**, %struct.gs_memory_s*)* @gs_build_function_0 }, %struct.build_function_type_s { i32 2, i32 (%struct.gs_context_state_s*, %struct.ref_s*, %struct.gs_function_params_s*, i32, %struct.gs_function_s**, %struct.gs_memory_s*)* @gs_build_function_2 }, %struct.build_function_type_s { i32 3, i32 (%struct.gs_context_state_s*, %struct.ref_s*, %struct.gs_function_params_s*, i32, %struct.gs_function_s**, %struct.gs_memory_s*)* @gs_build_function_3 }, %struct.build_function_type_s zeroinitializer], align 16
@build_function_type_table_count = constant i32 4, align 4
@interp1_op_defs = external constant [0 x %struct.op_def], align 8
@interp2_op_defs = external constant [0 x %struct.op_def], align 8
@zbseq_l2_op_defs = external constant [0 x %struct.op_def], align 8
@zcolor1_op_defs = external constant [0 x %struct.op_def], align 8
@zht1_op_defs = external constant [0 x %struct.op_def], align 8
@zupath_l2_op_defs = external constant [0 x %struct.op_def], align 8
@zvmem2_op_defs = external constant [0 x %struct.op_def], align 8
@zdps1_l2_op_defs = external constant [0 x %struct.op_def], align 8
@ireclaim_l2_op_defs = external constant [0 x %struct.op_def], align 8
@zcharx_op_defs = external constant [0 x %struct.op_def], align 8
@zchar1_op_defs = external constant [0 x %struct.op_def], align 8
@zfont1_op_defs = external constant [0 x %struct.op_def], align 8
@zmisc1_op_defs = external constant [0 x %struct.op_def], align 8
@zusparam_op_defs = external constant [0 x %struct.op_def], align 8
@zmisc2_op_defs = external constant [0 x %struct.op_def], align 8
@zchar2_op_defs = external constant [0 x %struct.op_def], align 8
@zfont2_op_defs = external constant [0 x %struct.op_def], align 8
@zchar42_op_defs = external constant [0 x %struct.op_def], align 8
@zfont42_op_defs = external constant [0 x %struct.op_def], align 8
@zfrsd_op_defs = external constant [0 x %struct.op_def], align 8
@zfcid0_op_defs = external constant [0 x %struct.op_def], align 8
@zfcid1_op_defs = external constant [0 x %struct.op_def], align 8
@zcrd_l2_op_defs = external constant [0 x %struct.op_def], align 8
@zfcmap_op_defs = external constant [0 x %struct.op_def], align 8
@zcfont_op_defs = external constant [0 x %struct.op_def], align 8
@zfont0_op_defs = external constant [0 x %struct.op_def], align 8
@zfdcte_op_defs = external constant [0 x %struct.op_def], align 8
@zfdctd_op_defs = external constant [0 x %struct.op_def], align 8
@zfdecode_op_defs = external constant [0 x %struct.op_def], align 8
@zfilter2_op_defs = external constant [0 x %struct.op_def], align 8
@ziodev2_l2_op_defs = external constant [0 x %struct.op_def], align 8
@zdevice2_l2_op_defs = external constant [0 x %struct.op_def], align 8
@zmedia2_l2_op_defs = external constant [0 x %struct.op_def], align 8
@zpcolor_l2_op_defs = external constant [0 x %struct.op_def], align 8
@zarith_op_defs = external constant [0 x %struct.op_def], align 8
@zarray_op_defs = external constant [0 x %struct.op_def], align 8
@zcontrol1_op_defs = external constant [0 x %struct.op_def], align 8
@zcontrol2_op_defs = external constant [0 x %struct.op_def], align 8
@zcontrol3_op_defs = external constant [0 x %struct.op_def], align 8
@zdict1_op_defs = external constant [0 x %struct.op_def], align 8
@zdict2_op_defs = external constant [0 x %struct.op_def], align 8
@zfile_op_defs = external constant [0 x %struct.op_def], align 8
@zfile1_op_defs = external constant [0 x %struct.op_def], align 8
@zfileio1_op_defs = external constant [0 x %struct.op_def], align 8
@zfileio2_op_defs = external constant [0 x %struct.op_def], align 8
@zfilter_op_defs = external constant [0 x %struct.op_def], align 8
@zfproc_op_defs = external constant [0 x %struct.op_def], align 8
@zgeneric_op_defs = external constant [0 x %struct.op_def], align 8
@ziodev_op_defs = external constant [0 x %struct.op_def], align 8
@zmath_op_defs = external constant [0 x %struct.op_def], align 8
@zalg_op_defs = external constant [0 x %struct.op_def], align 8
@zmisc_op_defs = external constant [0 x %struct.op_def], align 8
@zpacked_op_defs = external constant [0 x %struct.op_def], align 8
@zrelbit_op_defs = external constant [0 x %struct.op_def], align 8
@zstack_op_defs = external constant [0 x %struct.op_def], align 8
@zstring_op_defs = external constant [0 x %struct.op_def], align 8
@zsysvm_op_defs = external constant [0 x %struct.op_def], align 8
@ztoken_op_defs = external constant [0 x %struct.op_def], align 8
@ztype_op_defs = external constant [0 x %struct.op_def], align 8
@zvmem_op_defs = external constant [0 x %struct.op_def], align 8
@zbfont_op_defs = external constant [0 x %struct.op_def], align 8
@zchar_a_op_defs = external constant [0 x %struct.op_def], align 8
@zchar_b_op_defs = external constant [0 x %struct.op_def], align 8
@zcolor_op_defs = external constant [0 x %struct.op_def], align 8
@zcolor_ext_op_defs = external constant [0 x %struct.op_def], align 8
@zdevice_op_defs = external constant [0 x %struct.op_def], align 8
@zfont_op_defs = external constant [0 x %struct.op_def], align 8
@zfontenum_op_defs = external constant [0 x %struct.op_def], align 8
@zgstate1_op_defs = external constant [0 x %struct.op_def], align 8
@zgstate2_op_defs = external constant [0 x %struct.op_def], align 8
@zgstate3_op_defs = external constant [0 x %struct.op_def], align 8
@zdfilter_op_defs = external constant [0 x %struct.op_def], align 8
@zht_op_defs = external constant [0 x %struct.op_def], align 8
@zimage_op_defs = external constant [0 x %struct.op_def], align 8
@zmatrix_op_defs = external constant [0 x %struct.op_def], align 8
@zmatrix2_op_defs = external constant [0 x %struct.op_def], align 8
@zpaint_op_defs = external constant [0 x %struct.op_def], align 8
@zpath_op_defs = external constant [0 x %struct.op_def], align 8
@pantone_op_defs = external constant [0 x %struct.op_def], align 8
@zdscpars_op_defs = external constant [0 x %struct.op_def], align 8
@zfapi_op_defs = external constant [0 x %struct.op_def], align 8
@zfbcp_op_defs = external constant [0 x %struct.op_def], align 8
@zpath1_op_defs = external constant [0 x %struct.op_def], align 8
@zht2_l2_op_defs = external constant [0 x %struct.op_def], align 8
@zcssepr_l2_op_defs = external constant [0 x %struct.op_def], align 8
@zfsample_op_defs = external constant [0 x %struct.op_def], align 8
@zfunc_op_defs = external constant [0 x %struct.op_def], align 8
@zchar32_op_defs = external constant [0 x %struct.op_def], align 8
@zfont32_op_defs = external constant [0 x %struct.op_def], align 8
@zfimscale_op_defs = external constant [0 x %struct.op_def], align 8
@zform_op_defs = external constant [0 x %struct.op_def], align 8
@zimage3_op_defs = external constant [0 x %struct.op_def], align 8
@zmisc3_op_defs = external constant [0 x %struct.op_def], align 8
@zcolor3_l3_op_defs = external constant [0 x %struct.op_def], align 8
@zshade_op_defs = external constant [0 x %struct.op_def], align 8
@zfzlib_op_defs = external constant [0 x %struct.op_def], align 8
@ztrans1_op_defs = external constant [0 x %struct.op_def], align 8
@ztrans2_op_defs = external constant [0 x %struct.op_def], align 8
@zfmd5_op_defs = external constant [0 x %struct.op_def], align 8
@zfsha2_op_defs = external constant [0 x %struct.op_def], align 8
@zfarc4_op_defs = external constant [0 x %struct.op_def], align 8
@zfaes_op_defs = external constant [0 x %struct.op_def], align 8
@zicc_ll3_op_defs = external constant [0 x %struct.op_def], align 8
@zpdfops_op_defs = external constant [0 x %struct.op_def], align 8
@zcontext1_op_defs = external constant [0 x %struct.op_def], align 8
@zcontext2_op_defs = external constant [0 x %struct.op_def], align 8
@zdps_op_defs = external constant [0 x %struct.op_def], align 8
@zdpnext_op_defs = external constant [0 x %struct.op_def], align 8
@zfjbig2_op_defs = external constant [0 x %struct.op_def], align 8
@zfjpx_op_defs = external constant [0 x %struct.op_def], align 8
@op_defs_all = constant [111 x %struct.op_def*] [%struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @interp1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @interp2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zbseq_l2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zcolor1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zht1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zupath_l2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zvmem2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zdps1_l2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @ireclaim_l2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zcharx_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zchar1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfont1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zmisc1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zusparam_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zmisc2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zchar2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfont2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zchar42_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfont42_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfrsd_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfcid0_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfcid1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zcrd_l2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfcmap_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zcfont_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfont0_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfdcte_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfdctd_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfdecode_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfilter2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @ziodev2_l2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zdevice2_l2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zmedia2_l2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zpcolor_l2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zarith_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zarray_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zcontrol1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zcontrol2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zcontrol3_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zdict1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zdict2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfile_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfile1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfileio1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfileio2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfilter_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfproc_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zgeneric_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @ziodev_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zmath_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zalg_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zmisc_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zpacked_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zrelbit_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zstack_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zstring_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zsysvm_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @ztoken_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @ztype_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zvmem_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zbfont_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zchar_a_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zchar_b_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zcolor_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zcolor_ext_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zdevice_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfont_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfontenum_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zgstate1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zgstate2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zgstate3_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zdfilter_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zht_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zimage_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zmatrix_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zmatrix2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zpaint_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zpath_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @pantone_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zdscpars_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfapi_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfbcp_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zpath1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zht2_l2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zcssepr_l2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfsample_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfunc_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zchar32_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfont32_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfimscale_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zform_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zimage3_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zmisc3_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zcolor3_l3_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zshade_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfzlib_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @ztrans1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @ztrans2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfmd5_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfsha2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfarc4_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfaes_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zicc_ll3_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zpdfops_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zcontext1_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zcontext2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zdps_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zdpnext_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfjbig2_op_defs, i32 0, i32 0), %struct.op_def* getelementptr inbounds ([0 x %struct.op_def], [0 x %struct.op_def]* @zfjpx_op_defs, i32 0, i32 0), %struct.op_def* null], align 16
@op_def_count = constant i32 1760, align 4
@i_plugin_table = constant [1 x i32 (%struct.i_plugin_client_memory_s*, %struct.i_plugin_instance_s**)*] zeroinitializer, align 8

declare i32 @gs_build_function_4(%struct.gs_context_state_s*, %struct.ref_s*, %struct.gs_function_params_s*, i32, %struct.gs_function_s**, %struct.gs_memory_s*) #0

declare i32 @gs_build_function_0(%struct.gs_context_state_s*, %struct.ref_s*, %struct.gs_function_params_s*, i32, %struct.gs_function_s**, %struct.gs_memory_s*) #0

declare i32 @gs_build_function_2(%struct.gs_context_state_s*, %struct.ref_s*, %struct.gs_function_params_s*, i32, %struct.gs_function_s**, %struct.gs_memory_s*) #0

declare i32 @gs_build_function_3(%struct.gs_context_state_s*, %struct.ref_s*, %struct.gs_function_params_s*, i32, %struct.gs_function_s**, %struct.gs_memory_s*) #0

attributes #0 = { "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="false" "no-infs-fp-math"="false" "no-nans-fp-math"="false" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+sse,+sse2" "unsafe-fp-math"="false" "use-soft-float"="false" }

!llvm.ident = !{!0}

!0 = !{!"clang version 3.7.0 (tags/RELEASE_370/final)"}
