# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='main_filename',
            field=models.TextField(default='main'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='opt_filename',
            field=models.TextField(default='opt'),
            preserve_default=False,
        ),
    ]
