# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20160420_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('dirname', models.TextField()),
                ('filename', models.TextField()),
                ('retcode', models.IntegerField()),
                ('stdout', models.TextField()),
                ('stderr', models.TextField()),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Submission')),
            ],
        ),
        migrations.RemoveField(
            model_name='validationunit',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='validationunit',
            name='hint',
        ),
        migrations.RemoveField(
            model_name='validationunit',
            name='src',
        ),
        migrations.RemoveField(
            model_name='validationunit',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='validationunit',
            name='tgt',
        ),
        migrations.AddField(
            model_name='validationunit',
            name='dirname',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validationunit',
            name='translation_unit',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='submission.TranslationUnit'),
            preserve_default=False,
        ),
    ]
