# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20160421_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationunit',
            name='retcode',
            field=models.IntegerField(null=True),
        ),
    ]
