# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_auto_20160421_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validationunit',
            old_name='dirname',
            new_name='basename',
        ),
        migrations.AddField(
            model_name='validationunit',
            name='retcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='validationunit',
            name='stderr',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validationunit',
            name='stdout',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
