# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20160421_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
