# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_submission_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='opt_options',
            new_name='opt_pass',
        ),
    ]
